"""v1.1 detection engine, layer 2 (CONTRACTS_v11.md §8/§12, C3 round): the GAZETTEER —
OBEC, KATASTER, ULICA and gazetteer-driven MENO. Text-in, spans-out. No file I/O beyond
the bundled read-only data files, no docx/pdf, no ground truth, no import of corpus/ or
eval/.

context.md §4.2: the lists are finite, public and shipped with the app (LICENSES.md records
every source and licence). They are a RECALL AID, not an authority — a place or name absent
from them is still reachable through the anchor detectors and the user's known-entity list.

The data files are read-only inputs built by ``tools/build_gazetteer.py``; this module never
writes them and never regenerates them.

DECLENSION (context.md §5, the whole point of this module)
----------------------------------------------------------
``Košice`` must match ``Košiciach`` / ``Košíc`` / ``Košiciam``; ``Michalovce`` must match
``Michalovciach`` / ``Michaloviec``. Matching is therefore by STEM, computed by
``detect.declension.stem`` — the project's single Slovak stemmer. This module does not
reimplement stemming, does not widen the suffix inventory, and does not tokenize by hand: it
reuses ``detect.declension._tokens`` so token boundaries and offsets are identical to the
ones the stemmer was written against. (Underscore-private, deliberately: a second tokenizer
that drifted from the stemmer's edge-punctuation handling would silently shift spans, and the
writers slice the output document by offsets.)

THE DISCRIMINATOR is untouched and is exercised through the surname index: ``stem("Kováčovej")
== stem("Kováč")`` so a possessive declension of a name matches, while ``stem("Kováčskej")``
keeps the ``-sk-`` derivational infix and therefore does not. Nothing here adds adjectival
endings to the stemmer.

Each stem index is built ONCE per data file and cached; 12 000 street names are parsed on
first use, never at import time and never again per page.

KNOWN SUB-GAP (recorded in handoff.md, NOT fixed here)
-----------------------------------------------------
A multi-word place with an ADJECTIVAL modifier only matches its head noun in oblique cases:
``Banská Bystrica`` → ``Banskej Bystrici`` stems to (``banskej``, ``bystric``) and the
modifier's stem does not meet the nominative's, because ``-ej`` is an adjectival ending and is
deliberately absent from the stemmer's closed inventory. Fixing it by adding adjectival
endings would destroy the discriminator, so it is NOT fixed. Instead every multi-word entry is
ALSO indexed by its head noun, and a head-noun-only hit is emitted into the REVIEW bucket
(``auto=False``): the reviewer still sees ``Bystrici``, but a bare head noun (``Ves``,
``Streda``) is too weak to auto-redact on its own.

BUCKETING (contract §4 type names; §12 for ULICA)
-------------------------------------------------
* ``OBEC`` (obce.json), ``KATASTER`` (katastralne_uzemia.json) — ``auto=True``.
* ``ULICA`` (ulice.json) — ``auto=True`` ONLY when the street name is followed by a house
  number or preceded by ``ul.`` / ``ulica`` / ``nám.`` / ``námestie`` / ``trieda`` / ``cesta``
  (case-insensitive). **A bare street name is not emitted at all.** Many Slovak streets are
  named after ordinary nouns, and 12 000 of them matched unanchored would flood a document;
  contract §12 (ADDENDUM 1 R3) states the restriction as "matched ONLY when …", so an
  unanchored street is dropped rather than demoted.
* ``MENO`` — a surname alone is ``auto=False`` (too weak a signal to auto-redact); a given
  name immediately followed by a Capitalized token is the full personal name and is
  ``auto=True`` over BOTH tokens; a given name alone is ``auto=False``.

STOPLISTS
---------
``stoplist.json`` holds place/street names that are also ordinary Slovak words or legal
vocabulary (``Hora``, ``Lipa``, ``Most``, ``Článok``, ``Zmluva``, ``Súd``). A hit on one of
those never reaches the AUTO bucket on the strength of the word alone — it is DEMOTED to
``auto=False``, not dropped, so the reviewer keeps the chance to tick it. It IS auto when an
independent anchor confirms it: an address/place keyword within 25 characters before, or a
house number / PSČ immediately after. The stoplist is applied to single-token surfaces only —
``Nová`` is stoplisted, but ``Spišská Nová Ves`` is unambiguous and must stay auto.

``_SURNAME_COMMON_WORDS`` below is the surname-specific stoplist the sprint brief asks for
(``Hora``, ``Vlk``, ``Kráľ``, ``Sladký``, …). It lives here as a module constant rather than in
``stoplist.json`` for two reasons: the data file is machine-generated by
``tools/build_gazetteer.py`` and is about PLACE names (adding hand-written surname entries to
it would be silently discarded by the next regeneration), and its effect is different — a
surname hit is already ``auto=False``, so demotion would be a no-op; these entries are
SUPPRESSED entirely, because a review-bucket candidate on every capitalised ``Kráľ`` or
``Malý`` in running prose is noise that makes the review list unusable. Nothing is lost when
the word really is a surname: the given-name + Capitalized-token rule still emits the full
name with ``auto=True``.

This module never resolves overlaps against other detector modules, and emits both an OBEC
and a KATASTER candidate where the two registers share a name — that is by design; contract
§5's resolver in ``detect/core.py`` settles every cross-type collision.
"""
from __future__ import annotations

import functools
import json
import os
import re
import sys

from .config import DetectConfig
from .core import Candidate
from .declension import _tokens, stem

NBSP = " "
_SEP = f"[ {NBSP}]"


class GazetteerDataError(RuntimeError):
    """A bundled gazetteer file is missing, unreadable or the wrong shape.

    Raised loudly and by NAME instead of returning no matches. A gazetteer that quietly
    matches nothing is the worst failure mode this module has: every gate still passes while
    the shipped app stops redacting places and names. See anonymizer.spec — the JSON files are
    plain data, invisible to PyInstaller's import analysis, so the frozen build is exactly
    where this can happen.
    """


# --------------------------------------------------------------------------- data loading
_OBCE = "obce.json"
_KATASTER = "katastralne_uzemia.json"
_ULICE = "ulice.json"
_FIRST_NAMES = "first_names.json"
_SURNAMES = "surnames.json"
_STOPLIST = "stoplist.json"


def _data_dir() -> str:
    """The bundled data directory: under ``sys._MEIPASS`` in a frozen build (anonymizer.spec
    ships the JSONs to ``detect/gazetteer_data`` there), next to this package otherwise."""
    if getattr(sys, "frozen", False):
        return os.path.join(getattr(sys, "_MEIPASS", ""), "detect", "gazetteer_data")
    return os.path.join(os.path.dirname(os.path.abspath(__file__)), "gazetteer_data")


@functools.lru_cache(maxsize=None)
def _load_names(filename: str) -> tuple[str, ...]:
    path = os.path.join(_data_dir(), filename)
    try:
        with open(path, encoding="utf-8") as fh:
            raw = json.load(fh)
    except OSError as exc:
        raise GazetteerDataError(f"gazetteer data file missing or unreadable: {path}") from exc
    except (json.JSONDecodeError, UnicodeDecodeError) as exc:
        raise GazetteerDataError(f"gazetteer data file is corrupt: {path} ({exc})") from exc
    if not isinstance(raw, list) or not all(isinstance(x, str) for x in raw):
        raise GazetteerDataError(
            f"gazetteer data file has the wrong shape (expected a JSON array of strings): {path}"
        )
    return tuple(raw)


@functools.lru_cache(maxsize=None)
def _index(filename: str) -> tuple[dict[str, str], dict[str, tuple], dict[str, str]]:
    """(single, multi, head) stem indices for one data file. Built once, cached forever.

    ``single``: stem -> canonical, for one-word entries.
    ``multi``:  first-word stem -> tuple of (word stems, canonical), longest entry first.
    ``head``:   head-noun stem -> canonical, for multi-word entries. The head noun is the last
                word of the LEADING run of capitalised words, so ``Nová Ves nad Žitavou`` heads
                on ``Ves`` and not on ``Žitavou``.
    """
    single: dict[str, str] = {}
    multi: dict[str, list[tuple[tuple[str, ...], str]]] = {}
    head: dict[str, str] = {}
    for name in _load_names(filename):
        words = name.split()
        if not words:
            continue
        stems = tuple(stem(w) for w in words)
        if len(words) == 1:
            single.setdefault(stems[0], name)
            continue
        multi.setdefault(stems[0], []).append((stems, name))
        run = 0
        while run + 1 < len(words) and words[run + 1][:1].isupper():
            run += 1
        head.setdefault(stems[run], name)
    frozen_multi = {
        key: tuple(sorted(vals, key=lambda sv: len(sv[0]), reverse=True))
        for key, vals in multi.items()
    }
    return single, frozen_multi, head


@functools.lru_cache(maxsize=None)
def _stoplist_stems() -> frozenset[str]:
    return frozenset(stem(w) for w in _load_names(_STOPLIST))


def _clear_caches() -> None:
    """Drop every cached index. Exists for the data-loading tests, which repoint
    ``_data_dir`` at a temporary directory."""
    _load_names.cache_clear()
    _index.cache_clear()
    _stoplist_stems.cache_clear()


# ----------------------------------------------------------------------------- anchors
# Place/address context that independently confirms a stoplisted word really is a place.
_PLACE_ANCHOR_RE = re.compile(
    r"ul\.|ulica|ulici|nám\.|námest|trieda|cesta|obec|obci|obce|mesto|meste|mesta"
    r"|okres|kataster|katastrálne územie|k\.\s?ú\.|trvale bytom|bytom|bydlisko"
    r"|so sídlom|sídlo|na adrese|adresa|adrese|pobyt",
    re.IGNORECASE,
)
# Street-specific keyword, immediately before the street name (contract §12).
_STREET_KEYWORD_RE = re.compile(
    rf"(?:ul\.|ulica|nám\.|námestie|trieda|cesta){_SEP}+$", re.IGNORECASE
)
# A house number (optionally with an orientation suffix) or a PSČ right after the name.
_NUMBER_AFTER_RE = re.compile(
    rf"^,?{_SEP}*(?:\d{{3}}{_SEP}\d{{2}}|\d{{1,4}}(?:/[A-Za-z0-9]{{1,3}})?)(?!\d)"
)
_HOUSENUM_AFTER_RE = re.compile(rf"^{_SEP}+\d{{1,4}}(?:/[A-Za-z0-9]{{1,3}})?(?!\d)")
# A PSC specifically (spaced or contiguous five digits). Unlike a bare house number this is
# unambiguous address context even after an ordinary-word place name.
_PSC_AFTER_RE = re.compile(rf"^,?{_SEP}*(?:\d{{3}}{_SEP}\d{{2}}|\d{{5}})(?!\d)")

_ANCHOR_WINDOW = 25


def _place_anchored(text: str, start: int, end: int) -> bool:
    """Confirmation that a STOPLISTED word really is a place here.

    Only a place/address KEYWORD counts. The "number immediately after" signal was tried and
    removed: it fires on "Strana 3 z 12" (an ordinary page footer — "Strana" is both a real
    municipality name and the Slovak word for page/party), on "Clanok 5" and on "Priloha 2".
    A bare number after an ordinary word carries no address meaning, so as a confirmation
    signal for a word we have ALREADY flagged as ambiguous it is worthless — it re-admits
    exactly the collisions the stoplist exists to catch.

    A PSC is different and still counts: "Lipa 040 01" is unambiguous address context, because
    a five-digit postal code is not a page number or an article number. So the distinction is
    PSC yes, bare 1-4 digit house number no.

    A plain house number still anchors a NON-stoplisted street (see _street_anchored); this
    stricter rule applies only to the 79 hand-listed collision words."""
    return bool(
        _PLACE_ANCHOR_RE.search(text[max(0, start - _ANCHOR_WINDOW) : start])
        or _PSC_AFTER_RE.match(text[end:])
    )


def _street_anchored(text: str, start: int, end: int, *, stoplisted: bool = False) -> bool:
    """Is this token anchored strongly enough to call it a street?

    Normally either signal will do: an explicit street KEYWORD before it, or a house NUMBER
    after it. For a STOPLISTED word the trailing number is not good enough, and the corpus
    says why: "Strana" is a real street name in the Register adries and also the Slovak word
    for "page"/"party", so "Strana 3 z 12" — an ordinary page footer — matched the
    number-after rule and was auto-redacted as an address. "Článok 5" and "Príloha 2" are the
    same shape. A number after an ordinary word carries no address meaning whatsoever.

    So a stoplisted word must be confirmed by the street KEYWORD specifically. This is the one
    place in the gazetteer where precision beats recall, and it is narrow on purpose: it
    applies only to the 79 hand-listed collision words, and only to the weaker of the two
    anchors. "ul. Strana 3" still matches."""
    keyword = _STREET_KEYWORD_RE.search(text[max(0, start - _ANCHOR_WINDOW) : start])
    if stoplisted:
        return bool(keyword)
    return bool(keyword or _HOUSENUM_AFTER_RE.match(text[end:]))


# ------------------------------------------------------------------------- surname stoplist
# Ordinary Slovak words that are also real surnames. See the module docstring for why these
# live here and are SUPPRESSED rather than demoted.
_SURNAME_COMMON_WORDS = frozenset(
    {
        "Hora", "Vlk", "Kráľ", "Sladký", "Mladý", "Malý", "Veľký", "Dobrý", "Biely",
        "Čierny", "Bystrý", "Tichý", "Krátky", "Dlhý", "Sokol", "Holub", "Zajac", "Baran",
        "Kohút", "Vrabec", "Mráz", "Slovák", "Nemec", "Rybár", "Bača", "Richtár", "Sedliak",
        "Pekný", "Hlava", "Hruška", "Sviečka", "Zima", "Jeseň",
    }
)


@functools.lru_cache(maxsize=None)
def _surname_stop_stems() -> frozenset[str]:
    return frozenset(stem(w) for w in _SURNAME_COMMON_WORDS)


# -------------------------------------------------------------------------- token helpers
# A gazetteer token must look like a Slovak proper noun: an initial capital, at least one
# lowercase letter after it, and at least three characters. Measured on the demo contract,
# without these three conditions the register matched:
#   "VIN 1HGBH41JXMN109186"  -> ULICA "VIN"      (an ALL-CAPS abbreviation, and the register
#                                                 really does contain a street "Vin")
#   "Článok I" / "Článok II" -> KATASTER "I"/"II" (Roman numerals; the register contains
#                                                 one- and two-letter place names)
# None of these is a place in context, and all three are things a legal document contains on
# every page. The rule is the same shape as the single-character guard in
# detect/known_entities.py and exists for the same reason: a needle short or generic enough to
# match everywhere is not evidence, it is noise, and noise in the review list is what makes a
# reviewer start blind-approving (context.md 9).
_MIN_GAZETTEER_TOKEN = 3


def _capitalized(core: str) -> bool:
    return (
        len(core) >= _MIN_GAZETTEER_TOKEN
        and core[:1].isupper()
        and any(ch.islower() for ch in core[1:])
    )


def _adjacent(text: str, end: int, next_start: int) -> bool:
    """True when nothing but whitespace separates two tokens. Punctuation between them (a
    full stop, a comma) means they are not one name — ``"… bol Ján. Zmluva …"`` must not
    become ``Ján. Zmluva``."""
    return text[end:next_start].strip() == ""


# ---------------------------------------------------------------------------- place walk
def _match_multi(
    text: str,
    toks: list[tuple[str, int, int]],
    tstems: list[str],
    i: int,
    entries: tuple[tuple[tuple[str, ...], str], ...],
) -> int | None:
    """Index of the LAST token of the longest multi-word entry starting at token ``i``."""
    for stems, _canonical in entries:
        n = len(stems)
        if i + n > len(toks):
            continue
        if any(tstems[i + k] != stems[k] for k in range(n)):
            continue
        if any(not _adjacent(text, toks[i + k][2], toks[i + k + 1][1]) for k in range(n - 1)):
            continue
        return i + n - 1
    return None


def _place_hits(
    text: str,
    toks: list[tuple[str, int, int]],
    tstems: list[str],
    filename: str,
    type_: str,
) -> list[Candidate]:
    single, multi, head = _index(filename)
    out: list[Candidate] = []
    i = 0
    while i < len(toks):
        core, start, end = toks[i]
        if not _capitalized(core):
            i += 1
            continue
        s = tstems[i]
        last = _match_multi(text, toks, tstems, i, multi.get(s, ())) if s in multi else None
        if last is not None:
            out.append(_place_candidate(text, type_, start, toks[last][2]))
            i = last + 1
            continue
        if s in single:
            out.append(_place_candidate(text, type_, start, end))
        elif s in head:
            # head-noun-only hit on a multi-word place — the recorded sub-gap, review bucket
            out.append(Candidate(type_, text[start:end], start, end, False, "n/a"))
        i += 1
    return out


def _place_candidate(text: str, type_: str, start: int, end: int) -> Candidate:
    surface = text[start:end]
    auto = True
    if " " not in surface and stem(surface) in _stoplist_stems():
        auto = _place_anchored(text, start, end)
    return Candidate(type_, surface, start, end, auto, "n/a")


# --------------------------------------------------------------------------- street walk
def _street_hits(
    text: str, toks: list[tuple[str, int, int]], tstems: list[str]
) -> list[Candidate]:
    single, multi, _head = _index(_ULICE)
    out: list[Candidate] = []
    i = 0
    while i < len(toks):
        core, start, end = toks[i]
        if not _capitalized(core):
            i += 1
            continue
        s = tstems[i]
        last = _match_multi(text, toks, tstems, i, multi.get(s, ())) if s in multi else None
        if last is not None:
            span_end = toks[last][2]
            if _street_anchored(text, start, span_end):
                out.append(Candidate("ULICA", text[start:span_end], start, span_end, True, "n/a"))
                i = last + 1
                continue
            # The longer entry exists in the register ("Ulica Štúrova") but nothing anchors
            # it here, so it is dropped — and the walk does NOT skip its tokens: the inner
            # name may still be anchored on its own ("bydlisko Ulica Štúrova" anchors
            # "Štúrova" on the keyword "Ulica").
        if s in single and _street_anchored(text, start, end, stoplisted=s in _stoplist_stems()):
            out.append(Candidate("ULICA", text[start:end], start, end, True, "n/a"))
        i += 1
    return out


# ----------------------------------------------------------------------------- name walk
def _name_hits(
    text: str, toks: list[tuple[str, int, int]], tstems: list[str]
) -> list[Candidate]:
    given = _index(_FIRST_NAMES)[0]
    surnames = _index(_SURNAMES)[0]
    stopped = _surname_stop_stems()
    out: list[Candidate] = []
    i = 0
    while i < len(toks):
        core, start, end = toks[i]
        if not _capitalized(core):
            i += 1
            continue
        s = tstems[i]
        if s in given:
            nxt = toks[i + 1] if i + 1 < len(toks) else None
            if nxt is not None and _capitalized(nxt[0]) and _adjacent(text, end, nxt[1]):
                out.append(Candidate("MENO", text[start : nxt[2]], start, nxt[2], True, "n/a"))
                i += 2
                continue
            out.append(Candidate("MENO", core, start, end, False, "n/a"))
        elif s in surnames and s not in stopped:
            out.append(Candidate("MENO", core, start, end, False, "n/a"))
        i += 1
    return out


# --------------------------------------------------------------------------- entry point
def detect_gazetteer(text: str, config: DetectConfig) -> list[Candidate]:
    """Detect OBEC, KATASTER, ULICA and gazetteer MENO spans (contract §8).

    ``config`` carries no toggle relevant to this module (both DetectConfig fields govern
    checksum tagging and DATUM redaction); it is accepted to match the frozen per-module
    signature so the orchestrator's dispatch stays uniform.
    """
    del config
    toks = list(_tokens(text))
    if not toks:
        return []
    tstems = [stem(core) for core, _s, _e in toks]
    out: list[Candidate] = []
    out.extend(_place_hits(text, toks, tstems, _OBCE, "OBEC"))
    out.extend(_place_hits(text, toks, tstems, _KATASTER, "KATASTER"))
    out.extend(_street_hits(text, toks, tstems))
    out.extend(_name_hits(text, toks, tstems))
    return out
