"""v1.1 detection engine, layer 2 (CONTRACTS_v11.md §8/§12, C3 round): the GAZETTEER —
OBEC, KATASTER, ULICA and gazetteer-driven MENO. Text-in, spans-out. No file I/O beyond
the bundled read-only data files, no docx/pdf, no ground truth, no import of corpus/ or
eval/.

context.md §4.2: the lists are finite, public and shipped with the app (LICENSES.md records
every source and licence). They are a RECALL AID, not an authority — a place or name absent
from them is still reachable through the anchor detectors and the user's known-entity list.

The data files are read-only inputs built by ``tools/build_gazetteer.py``; this module never
writes them and never regenerates them.

DECLENSION (context.md §5, the whole point of this module)
----------------------------------------------------------
``Košice`` must match ``Košiciach`` / ``Košíc`` / ``Košiciam``; ``Michalovce`` must match
``Michalovciach`` / ``Michaloviec``. Matching is therefore by STEM, computed by
``detect.declension.stem`` — the project's single Slovak stemmer. This module does not
reimplement stemming, does not widen the suffix inventory, and does not tokenize by hand: it
reuses ``detect.declension._tokens`` so token boundaries and offsets are identical to the
ones the stemmer was written against. (Underscore-private, deliberately: a second tokenizer
that drifted from the stemmer's edge-punctuation handling would silently shift spans, and the
writers slice the output document by offsets.)

THE DISCRIMINATOR is untouched and is exercised through the surname index: ``stem("Kováčovej")
== stem("Kováč")`` so a possessive declension of a name matches, while ``stem("Kováčskej")``
keeps the ``-sk-`` derivational infix and therefore does not. Nothing here adds adjectival
endings to the stemmer.

Each stem index is built ONCE per data file and cached; 12 000 street names are parsed on
first use, never at import time and never again per page.

KNOWN SUB-GAP (recorded in handoff.md, NOT fixed here)
-----------------------------------------------------
A multi-word place with an ADJECTIVAL modifier only matches its head noun in oblique cases:
``Banská Bystrica`` → ``Banskej Bystrici`` stems to (``banskej``, ``bystric``) and the
modifier's stem does not meet the nominative's, because ``-ej`` is an adjectival ending and is
deliberately absent from the stemmer's closed inventory. Fixing it by adding adjectival
endings would destroy the discriminator, so it is NOT fixed. Instead every multi-word entry is
ALSO indexed by its head noun, and a head-noun-only hit is emitted into the REVIEW bucket
(``auto=False``): the reviewer still sees ``Bystrici``, but a bare head noun (``Ves``,
``Streda``) is too weak to auto-redact on its own.

BUCKETING (contract §4 type names; §12 for ULICA)
-------------------------------------------------
* ``OBEC`` (obce.json), ``KATASTER`` (katastralne_uzemia.json) — ``auto=True``.
* ``ULICA`` (ulice.json) — ``auto=True`` ONLY when the street name is followed by a house
  number or preceded by ``ul.`` / ``ulica`` / ``nám.`` / ``námestie`` / ``trieda`` / ``cesta``
  (case-insensitive). **A bare street name is not emitted at all.** Many Slovak streets are
  named after ordinary nouns, and 12 000 of them matched unanchored would flood a document;
  contract §12 (ADDENDUM 1 R3) states the restriction as "matched ONLY when …", so an
  unanchored street is dropped rather than demoted.
* ``MENO`` — a surname alone is ``auto=False`` (too weak a signal to auto-redact); a given
  name immediately followed by a Capitalized token is the full personal name and is
  ``auto=True`` over BOTH tokens; a given name alone is ``auto=False``.

STOPLISTS
---------
``stoplist.json`` holds place/street names that are also ordinary Slovak words or legal
vocabulary (``Hora``, ``Lipa``, ``Most``, ``Článok``, ``Zmluva``, ``Súd``). A hit on one of
those never reaches the AUTO bucket on the strength of the word alone — it is DEMOTED to
``auto=False``, not dropped, so the reviewer keeps the chance to tick it. It IS auto when an
independent anchor confirms it: an address/place keyword within 25 characters before, or a
house number / PSČ immediately after. The stoplist is applied to single-token surfaces only —
``Nová`` is stoplisted, but ``Spišská Nová Ves`` is unambiguous and must stay auto.

``_SURNAME_COMMON_WORDS`` below is the surname-specific stoplist the sprint brief asks for
(``Hora``, ``Vlk``, ``Kráľ``, ``Sladký``, …). It lives here as a module constant rather than in
``stoplist.json`` for two reasons: the data file is machine-generated by
``tools/build_gazetteer.py`` and is about PLACE names (adding hand-written surname entries to
it would be silently discarded by the next regeneration), and its effect is different — a
surname hit is already ``auto=False``, so demotion would be a no-op; these entries are
SUPPRESSED entirely, because a review-bucket candidate on every capitalised ``Kráľ`` or
``Malý`` in running prose is noise that makes the review list unusable. Nothing is lost when
the word really is a surname: the given-name + Capitalized-token rule still emits the full
name with ``auto=True``.

This module never resolves overlaps against other detector modules, and emits both an OBEC
and a KATASTER candidate where the two registers share a name — that is by design; contract
§5's resolver in ``detect/core.py`` settles every cross-type collision.
"""
from __future__ import annotations

import functools
import json
import os
import re
import sys

from .config import DetectConfig
from .core import Candidate
from .declension import _tokens, stem
from .identifiers import ascii_fold, document_is_single_case

NBSP = " "
# v1.1 SEPARATOR WIDENING (red-team round 2, finding R2-1). This class used to be exactly
# a space or an NBSP. That accepted the one spelling the corpus generator writes and
# rejected every other way the same text reaches us: a TAB (a form-style DOCX table cell is
# tab-aligned), TWO SPACES (column padding), or a LINE BREAK (a PDF text layer wraps on
# every page). Measured over 2559 corpus surfaces, a line break in these positions took
# overall detection robustness to 0.113 and CISLO_KLIENTA to 0.000 -- the very type whose
# anchor was widened after it leaked a client number out of a wrapped PDF. That earlier fix
# widened the separator BETWEEN THE WORDS OF AN ANCHOR and not the one between an anchor
# and its VALUE, so a wrap one word later leaked the same number again.
#
# The class below is horizontal whitespace only -- space, NBSP, tab -- with line breaks
# still EXCLUDED, because a separator INSIDE a surface must not join two lines into one
# phone number. Anchor-to-value separators are widened to full whitespace separately.
_SEP = '[^\\S\\n\\r]'


class GazetteerDataError(RuntimeError):
    """A bundled gazetteer file is missing, unreadable or the wrong shape.

    Raised loudly and by NAME instead of returning no matches. A gazetteer that quietly
    matches nothing is the worst failure mode this module has: every gate still passes while
    the shipped app stops redacting places and names. See anonymizer.spec — the JSON files are
    plain data, invisible to PyInstaller's import analysis, so the frozen build is exactly
    where this can happen.
    """


# --------------------------------------------------------------------------- data loading
_OBCE = "obce.json"
_KATASTER = "katastralne_uzemia.json"
_ULICE = "ulice.json"
_FIRST_NAMES = "first_names.json"
_SURNAMES = "surnames.json"
_STOPLIST = "stoplist.json"


def _data_dir() -> str:
    """The bundled data directory: under ``sys._MEIPASS`` in a frozen build (anonymizer.spec
    ships the JSONs to ``detect/gazetteer_data`` there), next to this package otherwise."""
    if getattr(sys, "frozen", False):
        return os.path.join(getattr(sys, "_MEIPASS", ""), "detect", "gazetteer_data")
    return os.path.join(os.path.dirname(os.path.abspath(__file__)), "gazetteer_data")


@functools.lru_cache(maxsize=None)
def _load_names(filename: str) -> tuple[str, ...]:
    path = os.path.join(_data_dir(), filename)
    try:
        with open(path, encoding="utf-8") as fh:
            raw = json.load(fh)
    except OSError as exc:
        raise GazetteerDataError(f"gazetteer data file missing or unreadable: {path}") from exc
    except (json.JSONDecodeError, UnicodeDecodeError) as exc:
        raise GazetteerDataError(f"gazetteer data file is corrupt: {path} ({exc})") from exc
    if not isinstance(raw, list) or not all(isinstance(x, str) for x in raw):
        raise GazetteerDataError(
            f"gazetteer data file has the wrong shape (expected a JSON array of strings): {path}"
        )
    return tuple(raw)


@functools.lru_cache(maxsize=None)
def _index(filename: str) -> tuple[dict[str, str], dict[str, tuple], dict[str, str]]:
    """(single, multi, head) stem indices for one data file. Built once, cached forever.

    ``single``: stem -> canonical, for one-word entries.
    ``multi``:  first-word stem -> tuple of (word stems, canonical), longest entry first.
    ``head``:   head-noun stem -> canonical, for multi-word entries. The head noun is the last
                word of the LEADING run of capitalised words, so ``Nová Ves nad Žitavou`` heads
                on ``Ves`` and not on ``Žitavou``.
    """
    single: dict[str, str] = {}
    multi: dict[str, list[tuple[tuple[str, ...], str]]] = {}
    head: dict[str, str] = {}
    for name in _load_names(filename):
        words = name.split()
        if not words:
            continue
        stems = tuple(stem(w) for w in words)
        if len(words) == 1:
            single.setdefault(stems[0], name)
            continue
        multi.setdefault(stems[0], []).append((stems, name))
        run = 0
        while run + 1 < len(words) and words[run + 1][:1].isupper():
            run += 1
        head.setdefault(stems[run], name)
    frozen_multi = {
        key: tuple(sorted(vals, key=lambda sv: len(sv[0]), reverse=True))
        for key, vals in multi.items()
    }
    return single, frozen_multi, head


@functools.lru_cache(maxsize=None)
def _index_ascii(filename: str) -> tuple[dict[str, str], dict[str, tuple], dict[str, str]]:
    """A DIACRITIC-FOLDED mirror of ``_index`` (round-2 red-team, R2-2): "Kosice" (no
    diacritics -- a mutated document, or a lawyer who never learned to type them) must still
    meet ``Košice``'s stem, and the plain stem index is diacritic-EXACT because ``stem()``
    deliberately preserves them (the -sk-/-ck- discriminator is a consonant infix, untouched
    by folding vowels and consonant diacritics away).

    OFFSET-SAFE even though ``ascii_fold`` is not 1:1: the fold is applied only to the
    DICTIONARY KEY, never to the text a span is cut from. Every canonical value and every
    offset returned to a caller still comes from ``_index``'s own (unfolded) data and from
    the caller's own token span -- this function only widens which KEY reaches that unchanged
    data, exactly the way ``diacritic_pattern`` widens a regex pattern instead of folding the
    text it matches against."""
    single, multi, head = _index(filename)
    single_a: dict[str, str] = {ascii_fold(k): v for k, v in single.items()}
    multi_a: dict[str, list[tuple[tuple[str, ...], str]]] = {}
    for k, entries in multi.items():
        multi_a.setdefault(ascii_fold(k), []).extend(entries)
    head_a: dict[str, str] = {ascii_fold(k): v for k, v in head.items()}
    return single_a, {k: tuple(v) for k, v in multi_a.items()}, head_a


@functools.lru_cache(maxsize=None)
def _stoplist_stems() -> frozenset[str]:
    return frozenset(stem(w) for w in _load_names(_STOPLIST))


@functools.lru_cache(maxsize=None)
def _stoplist_stems_ascii() -> frozenset[str]:
    return frozenset(ascii_fold(s) for s in _stoplist_stems())


def _clear_caches() -> None:
    """Drop every cached index. Exists for the data-loading tests, which repoint
    ``_data_dir`` at a temporary directory."""
    _load_names.cache_clear()
    _index.cache_clear()
    _index_ascii.cache_clear()
    _stoplist_stems.cache_clear()
    _stoplist_stems_ascii.cache_clear()


# ----------------------------------------------------------------------------- anchors
# Place/address context that independently confirms a stoplisted word really is a place.
# CASE / DIACRITICS: both anchor tests below are context-WINDOW checks (never sliced, never
# a source of an offset), so they use technique B -- fold the window with ``ascii_fold`` and
# match against an ascii-spelled, lowercase pattern. That one fold covers case AND
# diacritics together, so no separate ``re.IGNORECASE`` is needed here.
_PLACE_ANCHOR_RE = re.compile(
    r"ul\.|ulica|ulici|nam\.|namest|trieda|cesta|obec|obci|obce|mesto|meste|mesta"
    r"|okres|kataster|katastralne uzemie|k\.\s?u\.|trvale bytom|bytom|bydlisko"
    r"|so sidlom|sidlo|na adrese|adresa|adrese|pobyt"
)
# Street-specific keyword, immediately before the street name (contract §12).
# _SEP_ANCHOR (line_break_mid, break-BETWEEN-words case): widened locally to `\s` for
# this ONE gap -- the keyword-to-street-name separator -- rather than by touching the
# module's shared `_SEP`, which also feeds `_NUMBER_AFTER_RE`/`_HOUSENUM_AFTER_RE`/
# `_PSC_AFTER_RE` (the number/PSC-after-the-name anchors for OBEC/KATASTER/ULICA, out of
# scope here). A PDF wrap after "ul." or "nám." is routine and killed the whole keyword
# anchor at the old horizontal-only separator; this gap is bounded by the `$` anchor
# against a fixed-length trailing window, never a terminator for a free-running value,
# so widening it cannot let anything swallow past where the street name starts.
_SEP_ANCHOR = r"\s"
_STREET_KEYWORD_RE = re.compile(rf"(?:ul\.|ulica|nam\.|namestie|trieda|cesta){_SEP_ANCHOR}+$")
# A house number (optionally with an orientation suffix) or a PSČ right after the name.
_NUMBER_AFTER_RE = re.compile(
    rf"^,?{_SEP}*(?:\d{{3}}{_SEP}\d{{2}}|\d{{1,4}}(?:/[A-Za-z0-9]{{1,3}})?)(?!\d)"
)
_HOUSENUM_AFTER_RE = re.compile(rf"^{_SEP}+\d{{1,4}}(?:/[A-Za-z0-9]{{1,3}})?(?!\d)")
# A PSC specifically (spaced or contiguous five digits). Unlike a bare house number this is
# unambiguous address context even after an ordinary-word place name.
_PSC_AFTER_RE = re.compile(rf"^,?{_SEP}*(?:\d{{3}}{_SEP}\d{{2}}|\d{{5}})(?!\d)")

# The same keywords INFLECTED and FOLLOWING the name: "na Hlavnej ULICI", "na Štúrovom
# NÁMESTÍ". Matched on the ascii-folded text, so the accents in "námestí" need no alternatives.
# Bounded by a fixed window and anchored at the start of the text AFTER the name, so it cannot
# reach past the words immediately following it.
_STREET_KEYWORD_AFTER_RE = re.compile(
    rf"^{_SEP_ANCHOR}+(?:ulic[aeiuoy]|namest[ie][a-z]?|tried[aeuoy]|cest[aeuoy])\b"
)

_ANCHOR_WINDOW = 25


def _place_anchored(text: str, start: int, end: int) -> bool:
    """Confirmation that a STOPLISTED word really is a place here.

    Only a place/address KEYWORD counts. The "number immediately after" signal was tried and
    removed: it fires on "Strana 3 z 12" (an ordinary page footer — "Strana" is both a real
    municipality name and the Slovak word for page/party), on "Clanok 5" and on "Priloha 2".
    A bare number after an ordinary word carries no address meaning, so as a confirmation
    signal for a word we have ALREADY flagged as ambiguous it is worthless — it re-admits
    exactly the collisions the stoplist exists to catch.

    A PSC is different and still counts: "Lipa 040 01" is unambiguous address context, because
    a five-digit postal code is not a page number or an article number. So the distinction is
    PSC yes, bare 1-4 digit house number no.

    A plain house number still anchors a NON-stoplisted street (see _street_anchored); this
    stricter rule applies only to the 79 hand-listed collision words."""
    return bool(
        _PLACE_ANCHOR_RE.search(ascii_fold(text[max(0, start - _ANCHOR_WINDOW) : start]))
        or _PSC_AFTER_RE.match(text[end:])
    )


def _street_anchored(text: str, start: int, end: int, *, stoplisted: bool = False) -> bool:
    """Is this token anchored strongly enough to call it a street?

    Normally either signal will do: an explicit street KEYWORD before it, or a house NUMBER
    after it. For a STOPLISTED word the trailing number is not good enough, and the corpus
    says why: "Strana" is a real street name in the Register adries and also the Slovak word
    for "page"/"party", so "Strana 3 z 12" — an ordinary page footer — matched the
    number-after rule and was auto-redacted as an address. "Článok 5" and "Príloha 2" are the
    same shape. A number after an ordinary word carries no address meaning whatsoever.

    So a stoplisted word must be confirmed by the street KEYWORD specifically. This is the one
    place in the gazetteer where precision beats recall, and it is narrow on purpose: it
    applies only to the 79 hand-listed collision words, and only to the weaker of the two
    anchors. "ul. Strana 3" still matches."""
    keyword = _STREET_KEYWORD_RE.search(ascii_fold(text[max(0, start - _ANCHOR_WINDOW) : start]))
    # ... or an INFLECTED keyword AFTER the name. "na Hlavnej ulici" is how an address reads
    # when the street name is declined, and it puts the keyword on the other side and in the
    # locative ("ulici", not "ulica"). Looking only backwards made the declined form
    # unreachable -- the two halves of this only work together.
    if not keyword:
        keyword = _STREET_KEYWORD_AFTER_RE.match(ascii_fold(text[end : end + _ANCHOR_WINDOW]))
    if stoplisted:
        return bool(keyword)
    return bool(keyword or _HOUSENUM_AFTER_RE.match(text[end:]))


# ------------------------------------------------------------------------- surname stoplist
# Ordinary Slovak words that are also real surnames. See the module docstring for why these
# live here and are SUPPRESSED rather than demoted.
_SURNAME_COMMON_WORDS = frozenset(
    {
        "Hora", "Vlk", "Kráľ", "Sladký", "Mladý", "Malý", "Veľký", "Dobrý", "Biely",
        "Čierny", "Bystrý", "Tichý", "Krátky", "Dlhý", "Sokol", "Holub", "Zajac", "Baran",
        "Kohút", "Vrabec", "Mráz", "Slovák", "Nemec", "Rybár", "Bača", "Richtár", "Sedliak",
        "Pekný", "Hlava", "Hruška", "Sviečka", "Zima", "Jeseň",
        # "Sídlo" (the "so sídlom" / "Sídlo:" address anchor word) collides with a real
        # surname once the diacritic-folded lookup fallback is applied (R2-2): stem("Sídlo")
        # folds to "sidl", which some surname in surnames.json also ascii-folds to. Measured
        # on the corpus (zmluva_v11_041.docx): "Sídlo:" was emitted as a review-bucket MENO
        # candidate. Suppressed here exactly like the other common-word/surname collisions.
        "Sídlo",
    }
)


@functools.lru_cache(maxsize=None)
def _surname_stop_stems() -> frozenset[str]:
    return frozenset(stem(w) for w in _SURNAME_COMMON_WORDS)


@functools.lru_cache(maxsize=None)
def _surname_stop_stems_ascii() -> frozenset[str]:
    return frozenset(ascii_fold(s) for s in _surname_stop_stems())


# -------------------------------------------------------------------------- token helpers
# A gazetteer token must look like a Slovak proper noun: an initial capital, at least one
# lowercase letter after it, and at least three characters. Measured on the demo contract,
# without these three conditions the register matched:
#   "VIN 1HGBH41JXMN109186"  -> ULICA "VIN"      (an ALL-CAPS abbreviation, and the register
#                                                 really does contain a street "Vin")
#   "Článok I" / "Článok II" -> KATASTER "I"/"II" (Roman numerals; the register contains
#                                                 one- and two-letter place names)
# None of these is a place in context, and all three are things a legal document contains on
# every page. The rule is the same shape as the single-character guard in
# detect/known_entities.py and exists for the same reason: a needle short or generic enough to
# match everywhere is not evidence, it is noise, and noise in the review list is what makes a
# reviewer start blind-approving (context.md 9).
_MIN_GAZETTEER_TOKEN = 3

# CASE (round-2 red-team, R2-5/C-5): the Amendment-6 guard above needs a lowercase letter to
# exist AT ALL, which an all_caps/lowercase mutation removes from the entire unit -- the
# guard then rejects every place/street/name token regardless of whether it is a real
# gazetteer hit, punishing the STEM INDEX lookup (which still matches: stem("KOSICE") ==
# stem("Kosice")) for a precision guard that has no evidence left to test. Relaxed to "looks
# like a whole word, no digits" ONLY when `document_is_single_case` (detect/identifiers.py,
# shared across every module that needs this gate) says the unit itself has no
# capitalisation signal left to lose -- an ordinary mixed-case paragraph never reaches it.
# This does not re-admit "VIN" (redteam finding C-5): that unit is short (~11 letters between
# the label and the code), under the shared helper's length floor, so it still gets the
# STRICT guard even when it happens to be written in a single case. Unlike name_anchors.py
# and orgs.py, no right-boundary fix is needed here: `_capitalized` gates a single TOKEN
# (never a multi-token greedy run), so there is nothing for a relaxed match to swallow.
def _capitalized(core: str, *, relaxed: bool = False) -> bool:
    if len(core) < _MIN_GAZETTEER_TOKEN:
        return False
    if relaxed:
        return core.isalpha()
    return core[:1].isupper() and any(ch.islower() for ch in core[1:])


def _adjacent(text: str, end: int, next_start: int) -> bool:
    """True when nothing but whitespace separates two tokens. Punctuation between them (a
    full stop, a comma) means they are not one name — ``"… bol Ján. Zmluva …"`` must not
    become ``Ján. Zmluva``."""
    return text[end:next_start].strip() == ""


# ---------------------------------------------------------------------------- place walk
def _match_multi(
    text: str,
    toks: list[tuple[str, int, int]],
    tstems: list[str],
    i: int,
    entries: tuple[tuple[tuple[str, ...], str], ...],
) -> int | None:
    """Index of the LAST token of the longest multi-word entry starting at token ``i``."""
    for stems, _canonical in entries:
        n = len(stems)
        if i + n > len(toks):
            continue
        if any(tstems[i + k] != stems[k] for k in range(n)):
            continue
        if any(not _adjacent(text, toks[i + k][2], toks[i + k + 1][1]) for k in range(n - 1)):
            continue
        return i + n - 1
    return None


def _match_multi_folded(
    text: str,
    toks: list[tuple[str, int, int]],
    tstems: list[str],
    tstems_ascii: list[str],
    i: int,
    s: str,
    s_ascii: str,
    multi: dict[str, tuple],
    multi_ascii: dict[str, tuple],
) -> int | None:
    """``_match_multi``, tried first on the exact (diacritic-preserving) stem and, only if
    that misses, again on the diacritic-folded stem against the folded index (R2-2). Offset-
    safe: both attempts return a token INDEX, and every span the caller builds from it still
    comes from ``toks`` -- the original token positions, never a folded string."""
    if s in multi:
        last = _match_multi(text, toks, tstems, i, multi[s])
        if last is not None:
            return last
    if s_ascii in multi_ascii:
        return _match_multi(text, toks, tstems_ascii, i, multi_ascii[s_ascii])
    return None


def _place_hits(
    text: str,
    toks: list[tuple[str, int, int]],
    tstems: list[str],
    tstems_ascii: list[str],
    filename: str,
    type_: str,
    *,
    relaxed: bool,
) -> list[Candidate]:
    single, multi, head = _index(filename)
    single_a, multi_a, head_a = _index_ascii(filename)
    out: list[Candidate] = []
    i = 0
    while i < len(toks):
        core, start, end = toks[i]
        if not _capitalized(core, relaxed=relaxed):
            i += 1
            continue
        s, s_a = tstems[i], tstems_ascii[i]
        last = _match_multi_folded(text, toks, tstems, tstems_ascii, i, s, s_a, multi, multi_a)
        if last is not None:
            out.append(_place_candidate(text, type_, start, toks[last][2]))
            i = last + 1
            continue
        if s in single or s_a in single_a:
            out.append(_place_candidate(text, type_, start, end))
        elif s in head or s_a in head_a:
            # head-noun-only hit on a multi-word place — the recorded sub-gap, review bucket
            out.append(Candidate(type_, text[start:end], start, end, False, "n/a"))
        i += 1
    return out


def _place_candidate(text: str, type_: str, start: int, end: int) -> Candidate:
    surface = text[start:end]
    auto = True
    if " " not in surface and stem(surface) in _stoplist_stems():
        auto = _place_anchored(text, start, end)
    return Candidate(type_, surface, start, end, auto, "n/a")


# --------------------------------------------------------------------------- street walk
# --------------------------------------------------------------------- ULICA declension
# Slovak adjectival endings, by the nominative ending of the head word. Streets are adjectives
# far more often than nouns -- Hlavná, Krátka, Školská, Dlhý, Štúrova -- and an address puts
# them in the locative or genitive: "na Hlavnej ulici", "z Krátkej", "na Štúrovej".
#
# GENERATED, not stripped. detect/declension.py's suffix inventory excludes the plain
# adjectival -ej on purpose: that exclusion is the discriminator between a possessive form of
# a SURNAME ("Kovacovej", which IS the person) and an adjective derived from it ("Kovacskej",
# which is not). Widening the shared stemmer for streets would break names, so instead the
# street index gains the inflected forms and the stemmer is left exactly as it was.
_ADJ_FORMS = {
    # Feminine, BOTH endings. Slovak rhythmic shortening shortens the adjective ending after a
    # long stem syllable -- "hlavná" keeps -á, "krátka" shortens to -a -- and on the register
    # the short form is the MAJORITY: 4 708 head words end in -a against 2 324 in -á.
    "a": ("ej", "u", "ou", "e", "ych", "ymi"),      # feminine short: Krátka -> Krátkej ...
    "á": ("ej", "ú", "ou", "e", "ych", "ymi"),      # feminine long:  Hlavná -> Hlavnej ...
    "ý": ("eho", "emu", "om", "ym", "e", "ych"),    # masculine: Dlhý -> Dlhého / Dlhom ...
    "é": ("eho", "emu", "om", "ym"),                # neuter:   Dlhé -> Dlhého ...
}
# Possessive streets (Štúrova, Hviezdoslavova, Kollárova) end in -ova/-ina and decline like a
# feminine adjective. Restricted to those two suffixes: a street that is a NOUN ending in -a
# ("Lipa") declines differently, and generating adjectival forms for it would index words that
# are not the street.
_POSSESSIVE_SUFFIXES = ("ova", "ina")
_POSSESSIVE_FORMS = ("ovej", "ovu", "ovou", "inej", "inu", "inou")


def _declined_variants(name: str) -> list[str]:
    """Every inflected spelling of ``name``'s head word. Nominative is NOT included -- it is
    already indexed by the ordinary path."""
    head = name.split()[-1] if name.split() else name
    if len(head) < 4:
        return []
    lowered = head.lower()
    out: list[str] = []
    for suffix in _POSSESSIVE_SUFFIXES:
        if lowered.endswith(suffix):
            base = head[: -len(suffix)]
            out.extend(base + form for form in _POSSESSIVE_FORMS
                       if form.startswith(suffix[:2]))
            break
    else:
        endings = _ADJ_FORMS.get(head[-1])
        if endings:
            out.extend(head[:-1] + ending for ending in endings)
    prefix = name[: len(name) - len(head)]
    return [prefix + variant for variant in out]


@functools.lru_cache(maxsize=None)
def _street_declined_index() -> tuple[dict[str, str], dict[str, str]]:
    """(stem -> canonical, ascii-stem -> canonical) for the DECLINED forms of every street.

    Single-head-word entries only. A multi-word register entry ("Ulica Štúrova") already
    matches through the multi-word path on its own tokens, and its head word is covered here.
    """
    by_stem: dict[str, str] = {}
    by_stem_ascii: dict[str, str] = {}
    for name in _load_names(_ULICE):
        for variant in _declined_variants(name):
            words = variant.split()
            if not words:
                continue
            head = words[-1]
            by_stem.setdefault(stem(head), name)
            by_stem_ascii.setdefault(stem(ascii_fold(head)), name)
    return by_stem, by_stem_ascii


def _street_hits(
    text: str,
    toks: list[tuple[str, int, int]],
    tstems: list[str],
    tstems_ascii: list[str],
    *,
    relaxed: bool,
) -> list[Candidate]:
    single, multi, _head = _index(_ULICE)
    single_a, multi_a, _head_a = _index_ascii(_ULICE)
    out: list[Candidate] = []
    i = 0
    while i < len(toks):
        core, start, end = toks[i]
        if not _capitalized(core, relaxed=relaxed):
            i += 1
            continue
        s, s_a = tstems[i], tstems_ascii[i]
        last = _match_multi_folded(text, toks, tstems, tstems_ascii, i, s, s_a, multi, multi_a)
        if last is not None:
            span_end = toks[last][2]
            if _street_anchored(text, start, span_end):
                out.append(Candidate("ULICA", text[start:span_end], start, span_end, True, "n/a"))
                i = last + 1
                continue
            # The longer entry exists in the register ("Ulica Štúrova") but nothing anchors
            # it here, so it is dropped — and the walk does NOT skip its tokens: the inner
            # name may still be anchored on its own ("bydlisko Ulica Štúrova" anchors
            # "Štúrova" on the keyword "Ulica").
        declined, declined_a = _street_declined_index()
        if s in single or s_a in single_a or s in declined or s_a in declined_a:
            stoplisted = s in _stoplist_stems() or s_a in _stoplist_stems_ascii()
            if _street_anchored(text, start, end, stoplisted=stoplisted):
                out.append(Candidate("ULICA", text[start:end], start, end, True, "n/a"))
        i += 1
    return out


# ----------------------------------------------------------------------------- name walk
def _name_hits(
    text: str,
    toks: list[tuple[str, int, int]],
    tstems: list[str],
    tstems_ascii: list[str],
    *,
    relaxed: bool,
) -> list[Candidate]:
    given, _given_m, _given_h = _index(_FIRST_NAMES)
    given_a = _index_ascii(_FIRST_NAMES)[0]
    surnames = _index(_SURNAMES)[0]
    surnames_a = _index_ascii(_SURNAMES)[0]
    stopped = _surname_stop_stems()
    stopped_a = _surname_stop_stems_ascii()
    out: list[Candidate] = []
    i = 0
    while i < len(toks):
        core, start, end = toks[i]
        if not _capitalized(core, relaxed=relaxed):
            i += 1
            continue
        s, s_a = tstems[i], tstems_ascii[i]
        if s in given or s_a in given_a:
            nxt = toks[i + 1] if i + 1 < len(toks) else None
            if nxt is not None and _capitalized(nxt[0], relaxed=relaxed) and _adjacent(text, end, nxt[1]):
                out.append(Candidate("MENO", text[start : nxt[2]], start, nxt[2], True, "n/a"))
                i += 2
                continue
            out.append(Candidate("MENO", core, start, end, False, "n/a"))
        elif (s in surnames or s_a in surnames_a) and s not in stopped and s_a not in stopped_a:
            out.append(Candidate("MENO", core, start, end, False, "n/a"))
        i += 1
    return out


# --------------------------------------------------------------------------- entry point
def detect_gazetteer(text: str, config: DetectConfig) -> list[Candidate]:
    """Detect OBEC, KATASTER, ULICA and gazetteer MENO spans (contract §8).

    ``config`` carries no toggle relevant to this module (both DetectConfig fields govern
    checksum tagging and DATUM redaction); it is accepted to match the frozen per-module
    signature so the orchestrator's dispatch stays uniform.
    """
    del config
    toks = list(_tokens(text))
    if not toks:
        return []
    tstems = [stem(core) for core, _s, _e in toks]
    tstems_ascii = [ascii_fold(s) for s in tstems]
    relaxed = document_is_single_case(text)
    out: list[Candidate] = []
    out.extend(_place_hits(text, toks, tstems, tstems_ascii, _OBCE, "OBEC", relaxed=relaxed))
    out.extend(
        _place_hits(text, toks, tstems, tstems_ascii, _KATASTER, "KATASTER", relaxed=relaxed)
    )
    out.extend(_street_hits(text, toks, tstems, tstems_ascii, relaxed=relaxed))
    out.extend(_name_hits(text, toks, tstems, tstems_ascii, relaxed=relaxed))
    return out
