"""v1.1 detection engine, round B3 (CONTRACTS_v11.md §8/§12): ORG and NAZOV_BANKY.
Text-in, spans-out. Imports only ``re``, ``detect.core.Candidate``,
``detect.config.DetectConfig``. Never ``corpus/`` or ``eval/``.

ORG is the LAST Class A exclusion in ``eval/leak_gate.py``. An excluded type is an UNTESTED
type, so this module exists to let that exclusion be emptied — everything it claims is
exercised by ``tests/test_detect_orgs.py`` and by ``corpus/pii/orgs.py``.

NAZOV_BANKY is the gap found by the Vyhláška MS SR 482/2011 mapping (contract §12): clause
(f) requires the NAME of the bank or of the foreign-bank branch, and the v1 type list had no
such type. Both names are already registered in ``detect/core.py::_TYPE_PRECEDENCE``.

Neither type carries a checksum, so every Candidate here is ``auto=True, checksum="n/a"``.

ORG — WHY THE SUFFIX IS THE SIGNAL
----------------------------------
A Slovak company name is arbitrary ("Alfa Beta", "Stavby Východ", "Tatra Servis"): nothing in
the words themselves says "company". What IS reliable is the LEGAL-FORM SUFFIX the Obchodný
zákonník requires the name to carry — ``s.r.o.``, ``a.s.``, ``k.s.``, ``v.o.s.``, ``n.o.``,
``o.z.``, ``družstvo``, ``štátny podnik`` / ``š.p.``, ``j.s.a.``, ``akciová spoločnosť``. So
the rule is: match the capitalised token run IMMEDIATELY BEFORE the suffix and INCLUDE the
suffix in the span — the suffix is part of the company's name as written, and a redaction
that leaves ``s.r.o.`` standing alone next to a hole reads as a redaction of a company, which
is what the reviewer needs to see.

Per ADDENDUM 1 R2 (owner policy) company data is publicly accessible, so ambiguity here
resolves toward REDACT: the run is allowed to be up to four capitalised tokens long and a
preceding unrelated capitalised word ("Zmluva Alfa s.r.o.") is swallowed rather than risked.
No precision effort is spent on this type beyond the three hand-checked negatives in the
tests (sentence-initial capital, a COURT, a bare capitalised word).

A court is deliberately NOT an ORG: ``Okresný súd Košice`` carries no legal-form suffix and
is not matched by any anchor here. Vyhláška clause (j) exempts judges and court officials, so
a court's name is not PII under the decree at all.

MULTI-WORD ANCHORS MUST SURVIVE A LINE BREAK
--------------------------------------------
``detect/office_refs.py::_AWS`` exists because a PDF wrapped between the words of the anchor
"číslo klienta", the anchor stopped matching, and a client number LEAKED into the redacted
text layer. Every multi-word construct in this module is therefore written with ``\\s+`` (or
``\\s*`` around a dot) between its words: ``spol. s r.o.``, ``akciová spoločnosť``, ``štátny
podnik``, ``Obchodné meno``, ``pobočka zahraničnej banky``, and every multi-word bank name.
That covers a newline, an NBSP and any run of spaces in one expression.

NAZOV_BANKY — WHY THE LIST LIVES HERE, IN CODE
----------------------------------------------
The banks and foreign-bank branches operating in Slovakia are a CLOSED LIST, and there is no
bundled data file for it. It must NOT be added to ``detect/gazetteer_data/``: that directory
is machine-generated by ``tools/build_gazetteer.py``, and a hand-added entry would be silently
WIPED on the next regeneration — the same trap already documented for
``detect/gazetteer.py::_SURNAME_COMMON_WORDS``. So the list is a documented module constant
here, versioned with the code that reads it.

The closed list is a RECALL AID, not an authority: a bank absent from it is still reachable
through the anchors ``banka`` / ``banky`` / ``pobočka zahraničnej banky``, which claim the
capitalised run beside them.
"""
from __future__ import annotations

import re

from .config import DetectConfig
from .core import Candidate

NBSP = " "
_SP = f"[ {NBSP}]"  # a literal space or NBSP, exactly where Slovak typography allows one
# Anchor-word separator: ANY whitespace, newline included. See the module docstring — this is
# the detect/office_refs.py ``_AWS`` rule, and it applies to every multi-word construct below.
_AWS = r"\s+"

# ------------------------------------------------------------------------------ token shapes
# A name token: an initial capital (Slovak diacritics included) followed by letters, digits,
# ``&`` (J&T), ``+`` or a hyphen. A dot is deliberately EXCLUDED, so a token can never swallow
# the legal-form suffix that follows it.
_UPPER = "A-ZÁÄČĎÉÍĹĽŇÓÔŔŠŤÚÝŽ"
_NAMECHAR = "0-9A-Za-zÁÄČĎÉÍĹĽŇÓÔŔŠŤÚÝŽáäčďéíĺľňóôŕšťúýž&+\\-"
_TOK = rf"[{_UPPER}][{_NAMECHAR}]*"
# A LOWERCASE CONNECTOR INSIDE THE RUN. Slovak company names routinely carry one — "Kováč a
# Partneri", "Šimko a spol.", "Mladý & Syn" — and a run of strictly capitalised tokens stops
# dead at the "a". Measured against corpus/pii/orgs.py over 3000 seeds, that cost 335 of 3000
# ORG surfaces: the detector claimed "Partneri s.r.o." while ground truth said "Kováč a
# Partneri s.r.o.", so the leading words of the company name would have survived redaction.
# The run still STARTS and ENDS on a capitalised token, so a trailing bare "a" is never
# claimed.
_CONN = rf"(?i:a|and)(?![{_NAMECHAR}])|&"
# Up to four capitalised tokens: enough for "Erste Group Bank AG", short enough that a
# runaway capitalised sentence cannot be claimed whole.
_RUN = rf"{_TOK}(?:{_AWS}(?:(?:{_CONN}){_AWS})?{_TOK}){{0,3}}"
_TOK_RE = re.compile(_TOK)


def _dotted(letters: str) -> str:
    """A dotted abbreviation with every spacing variant that really occurs: ``s.r.o.``,
    ``s. r. o.``, ``s.r.o`` (no final dot), an NBSP or a line break anywhere a space can go.
    The trailing whitespace is INSIDE the optional-dot group, so a suffix written without its
    final dot never drags trailing spaces into the span."""
    return r"\s*\.\s*".join(letters) + r"(?:\s*\.)?"


# ------------------------------------------------------------------------ legal-form suffixes
# Longest / most specific alternative FIRST: Python's alternation takes the first that
# matches, and "spol. s r.o." must not be left to the bare "s.r.o." alternative.
_SUFFIX_ALTS = (
    rf"spoločnosť{_AWS}s{_AWS}ručením{_AWS}obmedzeným",
    rf"spol(?:\s*\.)?{_AWS}s{_AWS}" + _dotted("ro"),
    rf"akciová{_AWS}spoločnosť",
    rf"štátny{_AWS}podnik",
    r"družstvo",
    _dotted("jsa"),
    _dotted("vos"),
    _dotted("sro"),
    _dotted("as"),
    _dotted("ks"),
    _dotted("no"),
    _dotted("oz"),
    _dotted("šp"),
)
# ``(?i:...)`` scopes case-insensitivity to the SUFFIX ONLY. A global re.IGNORECASE would also
# case-fold ``_TOK``'s uppercase class and destroy the "capitalised run" requirement — the one
# precision condition ORG has.
_SUFFIX = "(?i:" + "|".join(_SUFFIX_ALTS) + ")"

# name run, then the suffix. A comma before the suffix is ordinary Slovak typography
# ("Alfa Beta, s. r. o.") and is part of the span.
_ORG_SUFFIX_RE = re.compile(rf"(?<!\w)({_RUN}(?:,)?\s+{_SUFFIX})")

# --------------------------------------------------------------------------- ORG field label
# "Obchodné meno[:] <value>"; the value runs to the end of the line or the end of the table
# cell — it stops at a newline, a tab, or 2+ consecutive spaces (a flattened table column),
# exactly as detect/office_refs.py::_NAZOV_UCTU_RE does. A single internal space is part of
# the value, so multi-word company names survive.
_ORG_LABEL_RE = re.compile(
    rf"(?i:obchodné{_AWS}meno|obchodná{_AWS}firma|názov{_AWS}spoločnosti){_SP}*:?{_SP}*"
    rf"([^\n\t]+?)(?={_SP}{{2,}}|\t|\n|$)"
)

# ----------------------------------------------------------------------- ORG office anchors
# ``corpus/templates/_common.py`` seeds "Advokátska kancelária <surname>" as an ORG ground
# truth — a company name with NO legal-form suffix. These office forms name the organisation,
# so the anchor phrase is INSIDE the span: "Advokátska kancelária Kováč" is the whole name.
_ORG_OFFICE_RE = re.compile(
    rf"(?<!\w)((?i:advokátska{_AWS}kancelária|notársky{_AWS}úrad|exekútorský{_AWS}úrad"
    rf"|znalecký{_AWS}ústav){_AWS}{_RUN})"
)


# ================================================================================ NAZOV_BANKY
# The banks and foreign-bank branches operating in Slovakia (Vyhláška MS SR 482/2011 clause
# (f)), with the abbreviations and marketing names that actually appear in contracts and
# statements. NOT a data file — see the module docstring: detect/gazetteer_data/ is
# machine-generated by tools/build_gazetteer.py and a hand-added entry there would be wiped on
# the next regeneration.
#
# Entries are matched case-insensitively, with any whitespace (newline included) between
# words, with or without a trailing legal-form suffix, and with or without a trailing
# "pobočka zahraničnej banky".
_BANKS = (
    "Slovenská sporiteľňa",
    "Všeobecná úverová banka",
    "VÚB banka",
    "VÚB",
    "Tatra banka",
    "Československá obchodná banka",
    "ČSOB",
    "Poštová banka",
    "Prima banka Slovensko",
    "Prima banka",
    "365.bank",
    "mBank",
    "UniCredit Bank Czech Republic and Slovakia",
    "UniCredit Bank",
    "Raiffeisen banka",
    "Raiffeisen",
    "OTP Banka Slovensko",
    "OTP Banka",
    "Fio banka",
    "J&T Banka",
    "Oberbank AG",
    "Oberbank",
    "Citibank Europe",
    "Citibank",
    "ING Bank N.V.",
    "ING Bank",
    "Komerční banka",
    "Privatbanka",
    "Slovenská záručná a rozvojová banka",
    "Exportno-importná banka Slovenskej republiky",
    "Wüstenrot stavebná sporiteľňa",
    "Prvá stavebná sporiteľňa",
    "ČSOB stavebná sporiteľňa",
    "BKS Bank AG",
    "BKS Bank",
    "Banka Slovenia",
)


def _literal(name: str) -> str:
    """A closed-list entry as a regex: every word escaped, every gap tolerant of a newline,
    an NBSP or a run of spaces (the ``_AWS`` rule — a bank name wrapped across a PDF line
    break must still match)."""
    return _AWS.join(re.escape(w) for w in name.split())


_BANK_NAMES = "(?i:" + "|".join(
    _literal(n) for n in sorted(_BANKS, key=len, reverse=True)
) + ")"
_POBOCKA = rf"(?i:pobočka{_AWS}zahraničnej{_AWS}banky)"
# The anchor words, in the cases a Slovak contract actually writes them.
_BANK_WORD = r"(?i:bank(?:a|y|e|ou|ám|ách))"

# A closed-list name, optionally trailed by a legal-form suffix and/or the foreign-branch
# phrase. Both tails are part of the bank's registered name as written, so both are in the
# span.
_BANK_RE = re.compile(
    rf"(?<!\w){_BANK_NAMES}(?!\w)(?:,?\s+{_SUFFIX})?(?:,?\s+{_POBOCKA})?"
)
# Anchored forms, for a bank that is not on the closed list.
_BANK_BEFORE_RE = re.compile(rf"(?<!\w)({_RUN}{_AWS}{_BANK_WORD})(?!\w)")
_BANK_POBOCKA_BEFORE_RE = re.compile(rf"(?<!\w)({_RUN})(?:,)?\s+{_POBOCKA}(?!\w)")
_BANK_AFTER_RE = re.compile(rf"(?:{_POBOCKA}|(?<!\w){_BANK_WORD}){_AWS}({_RUN})(?!\w)")

# Words that are the LABEL, not the name, when they stand next to the anchor. Without this,
# "Kód banky: 1100" emits "Kód" as a bank name, and the report then tells the reviewer the
# document names a bank called "Kód" — a report that cannot be checked against the document is
# the failure mode CONTRACTS_v11.md Amendment 5 was written about.
_ANCHOR_STOPWORDS = frozenset(
    {
        "kód", "kod", "číslo", "cislo", "názov", "nazov", "pobočka", "pobocka", "adresa",
        "sídlo", "sidlo", "účet", "ucet", "iban", "bic", "swift", "zmluva", "banka",
        "banky", "banke", "klient", "klienta", "majiteľ", "vlastník", "prevod", "platba",
        "suma", "výpis", "vypis", "strana", "článok", "clanok", "príloha", "priloha",
    }
)


def _trim_run(text: str, start: int, end: int) -> tuple[int, int] | None:
    """Drop leading stoplisted tokens from a capitalised run. Returns the trimmed span, or
    None when nothing survives (the whole run was a label)."""
    for m in _TOK_RE.finditer(text, start, end):
        if m.group().casefold() not in _ANCHOR_STOPWORDS:
            return m.start(), end
    return None


def _candidate(type_: str, text: str, start: int, end: int) -> Candidate:
    return Candidate(
        type=type_,
        surface=text[start:end],
        start=start,
        end=end,
        auto=True,
        checksum="n/a",
    )


def _detect_org(text: str) -> list[tuple[str, int, int]]:
    spans = [(m.start(1), m.end(1)) for m in _ORG_SUFFIX_RE.finditer(text)]
    spans += [(m.start(1), m.end(1)) for m in _ORG_LABEL_RE.finditer(text)]
    spans += [(m.start(1), m.end(1)) for m in _ORG_OFFICE_RE.finditer(text)]
    return [("ORG", s, e) for s, e in spans]


def _detect_nazov_banky(text: str) -> list[tuple[str, int, int]]:
    out = [("NAZOV_BANKY", m.start(), m.end()) for m in _BANK_RE.finditer(text)]
    for pattern in (_BANK_BEFORE_RE, _BANK_POBOCKA_BEFORE_RE, _BANK_AFTER_RE):
        for m in pattern.finditer(text):
            trimmed = _trim_run(text, m.start(1), m.end(1))
            if trimmed is not None:
                out.append(("NAZOV_BANKY", trimmed[0], trimmed[1]))
    return out


def detect_orgs(text: str, config: DetectConfig) -> list[Candidate]:
    """Detect ORG and NAZOV_BANKY spans (contract §8).

    ``config`` carries no toggle relevant to these two types (both DetectConfig fields govern
    checksum tagging and DATUM redaction, and neither type has a checksum); it is accepted to
    match the frozen per-module signature so the orchestrator's dispatch stays uniform.

    Spans are de-duplicated inside the module — the suffix rule and the field-label rule
    legitimately claim the same span on "Obchodné meno: Alfa Beta s.r.o." Overlapping (as
    opposed to identical) spans are NOT resolved here: contract §5's resolver in
    ``detect/core.py`` settles every collision, including the ones this module makes with
    itself.
    """
    del config
    seen: set[tuple[str, int, int]] = set()
    out: list[Candidate] = []
    for type_, start, end in _detect_org(text) + _detect_nazov_banky(text):
        key = (type_, start, end)
        if key in seen:
            continue
        seen.add(key)
        out.append(_candidate(type_, text, start, end))
    return out
